
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const defaultContext: LanguageContextType = {
  language: 'ar',
  setLanguage: () => {},
  t: () => '',
};

const LanguageContext = createContext<LanguageContextType>(defaultContext);

export const useLanguage = () => useContext(LanguageContext);

type LanguageProviderProps = {
  children: ReactNode;
};

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState('ar');
  const [translations, setTranslations] = useState<Record<string, Record<string, string>>>({
    en: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      blog: 'Blog',
      appointments: 'Appointments',
      contact: 'Contact',
      call_now: 'Call Now',
      switch_language: 'عربى',
      clinic_tag: 'Your Trusted Clinic',
      hero_title: 'Expert Dental Care in Mansoura',
      hero_description: 'Providing comprehensive dental services with a focus on quality, comfort, and cutting-edge technology.',
      book_now: 'Book Now',
      learn_services: 'Our Services',
      why_choose_us: 'Why Choose Us',
      feature_heading_start: 'Your Smile, Our',
      feature_heading_highlight: 'Priority',
      feature_heading_end: '!',
      feature_subheading: 'We are dedicated to providing the highest quality dental care in a comfortable and safe environment.',
      feature_safety_title: 'Safety & Hygiene',
      feature_safety_desc: 'Stringent sterilization protocols to ensure your safety.',
      feature_time_title: 'Time Efficiency',
      feature_time_desc: 'Prompt and efficient appointments to respect your time.',
      feature_quality_title: 'Quality & Precision',
      feature_quality_desc: 'High-quality materials and precise techniques for lasting results.',
      feature_technology_title: 'Advanced Technology',
      feature_technology_desc: 'Utilizing the latest dental technology for accurate diagnoses and effective treatments.',
      feature_care_title: 'Personalized Care',
      feature_care_desc: 'Individualized treatment plans tailored to your specific needs.',
      feature_team_title: 'Experienced Team',
      feature_team_desc: 'Highly skilled and compassionate dental professionals.',
      feature_comfort_title: 'Comfortable Environment',
      feature_comfort_desc: 'Relaxing and modern clinic designed for your comfort.',
      feature_preventive_title: 'Preventive Focus',
      feature_preventive_desc: 'Emphasis on preventive care to maintain your oral health.',
      about_us: 'About Us',
      about_heading_start: 'A Passion for',
      about_heading_highlight: 'Perfect Smiles',
      about_heading_end: '!',
      about_description: 'With over 15 years of experience, Dr. Mohamed Khashaba is dedicated to providing exceptional dental care using the latest techniques and technology.',
      experience_title: 'Years of Experience',
      experience_subtitle: '15+ years of providing top-notch dental care.',
      technology_title: 'Cutting-Edge Technology',
      technology_subtitle: 'Advanced equipment for accurate and efficient treatments.',
      learn_more_about: 'Learn More About Us',
      our_services: 'Our Services',
      services_heading_start: 'Comprehensive',
      services_heading_highlight: 'Dental Solutions',
      services_heading_end: '!',
      services_description: 'From general check-ups to advanced cosmetic procedures, we offer a wide range of services to meet all your dental needs.',
      dental_crowns_and_bridges: 'Dental Crowns and Bridges',
      dental_crowns_desc: 'Restore damaged or missing teeth with our custom-made crowns and bridges.',
      teeth_whitening: 'Teeth Whitening',
      teeth_whitening_desc: 'Brighten your smile with our safe and effective teeth whitening treatments.',
      dental_implants: 'Dental Implants',
      dental_implants_desc: 'Replace missing teeth with durable and natural-looking dental implants.',
      orthodontics: 'Orthodontics',
      orthodontics_desc: 'Straighten your teeth and improve your bite with our orthodontic solutions.',
      all_services: 'View All Services',
      years_experience: 'Years Experience',
      happy_patients: 'Happy Patients',
      successful_treatments: 'Successful Treatments',
      medical_awards: 'Medical Awards',
      testimonials: 'Testimonials',
      testimonials_heading_start: 'What Our',
      testimonials_heading_highlight: 'Patients Say',
      testimonials_heading_end: '!',
      testimonials_description: 'Read what our satisfied patients have to say about their experience at our clinic.',
      book_appointment: 'Book Appointment',
      appointment_heading_start: 'Schedule Your',
      appointment_heading_highlight: 'Visit Today',
      appointment_heading_end: '!',
      appointment_description: 'Book an appointment online and take the first step towards a healthier, more beautiful smile.',
      flexible_schedule_title: 'Flexible Scheduling',
      flexible_schedule_desc: 'We offer flexible appointment times to fit your busy schedule.',
      instant_confirmation_title: 'Instant Confirmation',
      instant_confirmation_desc: 'Receive instant confirmation of your appointment booking.',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      date: 'Date',
      message: 'Message',
      submit: 'Submit',
      blog_posts: 'Blog Posts',
      recent_posts: 'Recent Posts',
      share: 'Share',
      related_posts: 'Related Posts',
      leave_comment: 'Leave a Comment',
      your_comment: 'Your Comment',
      post_comment: 'Post Comment',
      address_clinic: 'Address Clinic',
      phone_number: 'Phone Number',
      send_us_message: 'Send us Message',
      subject: 'Subject',
      send_message: 'Send Message',
      all_rights_reserved: 'All Rights Reserved',
      developed_by: 'Developed by',
      journey_tag: 'Our Patient Journey',
      journey_heading_start: 'Your Path to a',
      journey_heading_highlight: 'Perfect Smile',
      journey_heading_end: '!',
      journey_subheading: 'Discover our seamless and patient-centered approach to dental care.',
      journey_step1_title: 'Book Appointment',
      journey_step1_desc: 'Schedule your visit online or by phone for a convenient time.',
      journey_step2_title: 'Initial Consultation',
      journey_step2_desc: 'Comprehensive examination and personalized treatment planning.',
      journey_step3_title: 'Treatment Phase',
      journey_step3_desc: 'Expert dental procedures using advanced technology.',
      journey_step4_title: 'Aftercare & Support',
      journey_step4_desc: 'Continued support and guidance for lasting oral health.',
      modern_facility: 'Modern Facility,',
      comfortable_environment: ' Comfortable Environment',
      clinic_gallery_description: 'Our state-of-the-art clinic is designed to provide a comfortable and relaxing experience for our patients.',
      our_clinic: 'Our Clinic',
      find_us: 'Find Us',
      visit_our: 'Visit Our',
      dental_clinic: 'Dental Clinic',
      location_description: 'We are conveniently located in Mansoura, Egypt. Visit us today for a consultation.',
      address: 'Address',
      working_hours: 'Working Hours',
      working_hours_details: 'Sunday to Thursday: 10AM - 8PM\nFriday: 2PM - 8PM\nSaturday: 10AM - 6PM',
      contact_info: 'Contact Info',
      map_placeholder: 'Clinic Location Map',
      about_service: 'About This Service',
      benefits: 'Benefits',
      treatment_process: 'Treatment Process',
      common_questions: 'Common Questions',
      initial_consultation: 'Initial Consultation',
      initial_consultation_desc: 'A thorough examination of your dental condition and discussion of treatment options.',
      preparation: 'Preparation',
      preparation_desc: 'Preparation of teeth and taking impressions for custom-made restorations.',
      fitting: 'Fitting',
      fitting_desc: 'Trying the restorations to ensure proper fit and appearance.',
      final_placement: 'Final Placement',
      final_placement_desc: 'Permanent cementing of the restorations with final adjustments for perfect bite and comfort.',
      treatment: 'Treatment',
      treatment_desc: 'Application of professional whitening agents to lighten tooth color.',
      aftercare: 'Aftercare',
      aftercare_desc: 'Instructions on maintaining results and preventing future staining.',
      implant_placement: 'Implant Placement',
      implant_placement_desc: 'Surgical placement of titanium implant into the jawbone.',
      healing_period: 'Healing Period',
      healing_period_desc: 'Allowing the implant to integrate with the bone over several months.',
      final_restoration: 'Final Restoration',
      final_restoration_desc: 'Placement of the crown on the implant for a natural look and function.',
      treatment_planning: 'Treatment Planning',
      treatment_planning_desc: 'Creating a customized plan for optimal teeth alignment.',
      braces_fitting: 'Braces Fitting',
      braces_fitting_desc: 'Attaching the orthodontic appliances to begin the alignment process.',
      regular_adjustments: 'Regular Adjustments',
      regular_adjustments_desc: 'Periodic visits to adjust the appliances and monitor progress.',
      book_appointment_desc: 'Schedule your appointment today to learn more about this service and how it can benefit you.',
      duration: 'Duration',
      minutes: 'minutes',
      expertise: 'Expertise',
      expert_dentist: 'Expert Dentist',
      safety: 'Safety',
      advanced_protocols: 'Advanced Safety Protocols',
      have_questions: 'Have Questions?',
      contact_us_desc: 'Our team is here to answer any questions you may have about this service.',
      ready_to_transform: 'Ready to Transform Your Smile?',
      transform_smile_desc: 'Schedule a consultation today and take the first step towards a healthier, more beautiful smile.',
      book_consultation: 'Book a Consultation',
      service_not_found: 'Service Not Found',
      service_not_found_desc: 'The requested service could not be found.',
      dental_crowns_benefit1: 'Restore natural chewing ability',
      dental_crowns_benefit2: 'Preserve jawbone structure',
      dental_crowns_benefit3: 'Natural appearance',
      dental_crowns_benefit4: 'Long-lasting solution',
      teeth_whitening_benefit1: 'Brighter smile',
      teeth_whitening_benefit2: 'Remove stains and discoloration',
      teeth_whitening_benefit3: 'Quick and safe procedure',
      teeth_whitening_benefit4: 'Immediate noticeable results',
      dental_implants_benefit1: 'Permanent tooth replacement',
      dental_implants_benefit2: 'Prevents bone loss',
      dental_implants_benefit3: 'Natural look and function',
      dental_implants_benefit4: 'No impact on adjacent teeth',
      orthodontics_benefit1: 'Correct teeth alignment',
      orthodontics_benefit2: 'Improve chewing function',
      orthodontics_benefit3: 'Multiple treatment options',
      orthodontics_benefit4: 'Lasting results',
      dental_crowns_faq1_question: 'How long do dental crowns last?',
      dental_crowns_faq1_answer: 'With proper care, dental crowns can last 10-15 years or even longer.',
      dental_crowns_faq2_question: 'Is the procedure painful?',
      dental_crowns_faq2_answer: 'The procedure is performed under local anesthesia, so you should not feel pain during treatment.',
      teeth_whitening_faq1_question: 'How long do teeth whitening results last?',
      teeth_whitening_faq1_answer: 'Results typically last 1-3 years, depending on diet and oral hygiene habits.',
      teeth_whitening_faq2_question: 'Is teeth whitening safe?',
      teeth_whitening_faq2_answer: 'Yes, professional teeth whitening is safe when performed by qualified dental professionals.',
      dental_implants_faq1_question: 'How long does the implant process take?',
      dental_implants_faq1_answer: 'The entire process typically takes 3-6 months, including healing time.',
      dental_implants_faq2_question: 'Are dental implants covered by insurance?',
      dental_implants_faq2_answer: 'Coverage varies by insurance plan. We can help you determine your coverage and financing options.',
      orthodontics_faq1_question: 'How long will I need to wear braces?',
      orthodontics_faq1_answer: 'Treatment time varies, but typically ranges from 12-24 months depending on complexity.',
      orthodontics_faq2_question: 'Can adults get orthodontic treatment?',
      orthodontics_faq2_answer: 'Yes, orthodontic treatment is effective for patients of all ages.',
      dr_name: 'Dr. Mohamed Khashaba',
      loading: 'Loading',
      working_hours_short: 'Sun-Thu: 10AM-8PM',
      clinic_address: 'Mansoura, Egypt',
      training_courses: 'Training Courses',
      free_consultation: 'Free Consultation',
      premium_services: 'Premium Services',
      specialized_dental_care: 'Specialized Dental Care',
      premium_services_desc: 'We offer premium dental services for patients with specific needs and high expectations.',
      smile_makeover: 'Smile Makeover',
      smile_makeover_desc: 'A complete transformation of your smile through a personalized combination of cosmetic procedures.',
      advanced_orthodontics: 'Advanced Orthodontics',
      advanced_orthodontics_desc: 'State-of-the-art orthodontic treatments for complex alignment issues and jaw problems.',
      laser_dentistry: 'Laser Dentistry',
      laser_dentistry_desc: 'Minimally invasive procedures using advanced laser technology for precise and comfortable treatments.',
      learn_more: 'Learn More',
      premium_consultation: 'Premium Consultation',
      services_title: 'Our Comprehensive Dental Services',
      services_subtitle: 'Expert care for all your dental needs',
      services_overview: 'We provide a wide range of dental services to meet all your oral health needs. From preventive care to advanced cosmetic procedures, we have you covered.',
      dental_care_excellence: 'Excellence in Dental Care',
      why_choose_us_desc: 'We combine expertise, advanced technology, and personalized care to provide the best dental experience.',
      experienced_team: 'Experienced Team',
      experienced_team_desc: 'Our team of highly skilled dental professionals is committed to delivering exceptional care.',
      advanced_technology: 'Advanced Technology',
      advanced_technology_desc: 'We use the latest dental technology to ensure accurate diagnoses and effective treatments.',
      learn_more_about_us: 'Learn More About Us',
      quality_point_1_title: 'Patient-Centered Care',
      quality_point_1_desc: 'We prioritize your comfort and well-being throughout your dental visit.',
      quality_point_2_title: 'Comprehensive Approach',
      quality_point_2_desc: 'Our holistic approach considers your overall health and specific dental needs.',
      quality_point_3_title: 'Transparent Communication',
      quality_point_3_desc: 'We explain all treatment options and costs before proceeding with any procedure.',
      quality_point_4_title: 'Continued Education',
      quality_point_4_desc: 'Our team regularly updates their knowledge and skills with the latest dental advancements.',
      insurance_payment: 'Insurance & Payment Options',
      insurance_payment_desc: 'We work with a variety of insurance providers and offer flexible payment options to make dental care accessible to all.',
      insurance_1: 'MetLife',
      insurance_2: 'Cigna',
      insurance_3: 'Aetna',
      insurance_4: 'Delta Dental',
      payment_questions: 'Payment Questions?',
      appointment_title: 'Ready to Schedule Your Visit?',
      gallery_images: 'Gallery Images',
      before_after: 'Before & After',
      gallery_title: 'Our Dental Transformations',
      gallery_subtitle: 'See the remarkable results we achieve for our patients',
      case_study: 'Case Study',
      view_all_cases: 'View All Cases',
      clinic_photos: 'Clinic Photos',
      clinic_photos_title: 'Our Modern Facility',
      clinic_photos_desc: 'Take a tour of our state-of-the-art dental clinic',
      contact_us: 'Contact Us'
    },
    ar: {
      home: 'الرئيسية',
      about: 'من نحن',
      services: 'خدماتنا',
      blog: 'المدونة',
      appointments: 'المواعيد',
      contact: 'اتصل بنا',
      call_now: 'اتصل الآن',
      switch_language: 'English',
      clinic_tag: 'عيادتك الموثوقة',
      hero_title: 'رعاية أسنان متخصصة في المنصورة',
      hero_description: 'تقديم خدمات شاملة لطب الأسنان مع التركيز على الجودة والراحة والتكنولوجيا المتطورة.',
      book_now: 'احجز الآن',
      learn_services: 'خدماتنا',
      why_choose_us: 'لماذا تختارنا',
      feature_heading_start: 'ابتسامتك،',
      feature_heading_highlight: 'أولويتنا',
      feature_heading_end: '!',
      feature_subheading: 'نحن ملتزمون بتقديم أعلى مستويات الجودة في رعاية الأسنان في بيئة مريحة وآمنة.',
      feature_safety_title: 'السلامة والنظافة',
      feature_safety_desc: 'بروتوكولات تعقيم صارمة لضمان سلامتك.',
      feature_time_title: 'كفاءة الوقت',
      feature_time_desc: 'مواعيد سريعة وفعالة احتراماً لوقتك.',
      feature_quality_title: 'الجودة والدقة',
      feature_quality_desc: 'مواد عالية الجودة وتقنيات دقيقة لنتائج دائمة.',
      feature_technology_title: 'تكنولوجيا متقدمة',
      feature_technology_desc: 'استخدام أحدث تقنيات طب الأسنان لتشخيص دقيق وعلاجات فعالة.',
      feature_care_title: 'رعاية شخصية',
      feature_care_desc: 'خطط علاج فردية مصممة خصيصًا لتلبية احتياجاتك الخاصة.',
      feature_team_title: 'فريق ذو خبرة',
      feature_team_desc: 'متخصصو طب الأسنان ذوو المهارات العالية والرحمة.',
      feature_comfort_title: 'بيئة مريحة',
      feature_comfort_desc: 'عيادة حديثة ومريحة مصممة لراحتك.',
      feature_preventive_title: 'التركيز الوقائي',
      feature_preventive_desc: 'التأكيد على الرعاية الوقائية للحفاظ على صحة الفم.',
      about_us: 'من نحن',
      about_heading_start: 'شغف',
      about_heading_highlight: 'الابتسامات المثالية',
      about_heading_end: '!',
      about_description: 'مع أكثر من 15 عامًا من الخبرة، يكرس الدكتور محمد خشبة جهوده لتقديم رعاية أسنان استثنائية باستخدام أحدث التقنيات.',
      experience_title: 'سنوات الخبرة',
      experience_subtitle: 'أكثر من 15 عامًا من تقديم رعاية أسنان عالية الجودة.',
      technology_title: 'تكنولوجيا متطورة',
      technology_subtitle: 'معدات متقدمة لعلاجات دقيقة وفعالة.',
      learn_more_about: 'اعرف المزيد عنا',
      our_services: 'خدماتنا',
      services_heading_start: 'حلول',
      services_heading_highlight: 'شاملة للأسنان',
      services_heading_end: '!',
      services_description: 'من الفحوصات العامة إلى الإجراءات التجميلية المتقدمة، نقدم مجموعة واسعة من الخدمات لتلبية جميع احتياجات أسنانك.',
      dental_crowns_and_bridges: 'تيجان وجسور الأسنان',
      dental_crowns_desc: 'استعادة الأسنان التالفة أو المفقودة باستخدام التيجان والجسور المصممة خصيصًا.',
      teeth_whitening: 'تبييض الأسنان',
      teeth_whitening_desc: 'تفتيح ابتسامتك من خلال علاجات تبييض الأسنان الآمنة والفعالة.',
      dental_implants: 'زراعة الأسنان',
      dental_implants_desc: 'استبدال الأسنان المفقودة بزراعة أسنان متينة وطبيعية المظهر.',
      orthodontics: 'تقويم الأسنان',
      orthodontics_desc: 'تقويم أسنانك وتحسين عضة الخاص بك مع حلول تقويم الأسنان لدينا.',
      all_services: 'عرض جميع الخدمات',
      years_experience: 'سنوات الخبرة',
      happy_patients: 'مرضى سعداء',
      successful_treatments: 'علاجات ناجحة',
      medical_awards: 'جوائز طبية',
      testimonials: 'الشهادات',
      testimonials_heading_start: 'ماذا يقول',
      testimonials_heading_highlight: 'مرضانا',
      testimonials_heading_end: '!',
      testimonials_description: 'اقرأ ما يقوله مرضانا الراضون عن تجربتهم في عيادتنا.',
      book_appointment: 'حجز موعد',
      appointment_heading_start: 'حدد موعد',
      appointment_heading_highlight: 'زيارتك اليوم',
      appointment_heading_end: '!',
      appointment_description: 'احجز موعدًا عبر الإنترنت واتخذ الخطوة الأولى نحو ابتسامة أكثر صحة وجمالاً.',
      flexible_schedule_title: 'جدولة مرنة',
      flexible_schedule_desc: 'نحن نقدم أوقات مواعيد مرنة لتناسب جدولك المزدحم.',
      instant_confirmation_title: 'تأكيد فوري',
      instant_confirmation_desc: 'تلقي تأكيد فوري لحجز موعدك.',
      name: 'الاسم',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      date: 'التاريخ',
      message: 'الرسالة',
      submit: 'إرسال',
      blog_posts: 'المشاركات',
      recent_posts: 'المشاركات الأخيرة',
      share: 'شارك',
      related_posts: 'المشاركات ذات الصلة',
      leave_comment: 'اترك تعليقاً',
      your_comment: 'تعليقك',
      post_comment: 'أضف تعليق',
      address_clinic: 'عنوان العيادة',
      phone_number: 'رقم الهاتف',
      send_us_message: 'أرسل لنا رسالة',
      subject: 'الموضوع',
      send_message: 'أرسل رسالة',
      all_rights_reserved: 'جميع الحقوق محفوظة',
      developed_by: 'طورت بواسطة',
      journey_tag: 'رحلة المريض',
      journey_heading_start: 'طريقك نحو',
      journey_heading_highlight: 'ابتسامة مثالية',
      journey_heading_end: '!',
      journey_subheading: 'اكتشف نهجنا السلس والمتمحور حول المريض في رعاية الأسنان.',
      journey_step1_title: 'حجز الموعد',
      journey_step1_desc: 'حدد زيارتك عبر الإنترنت أو عبر الهاتف في وقت مناسب.',
      journey_step2_title: 'استشارة أولية',
      journey_step2_desc: 'فحص شامل وتخطيط العلاج الشخصي.',
      journey_step3_title: 'مرحلة العلاج',
      journey_step3_desc: 'إجراءات طب الأسنان الخبيرة باستخدام التكنولوجيا المتقدمة.',
      journey_step4_title: 'الرعاية اللاحقة والدعم',
      journey_step4_desc: 'دعم وتوجيه مستمر لصحة الفم الدائمة.',
      modern_facility: 'مرفق حديث،',
      comfortable_environment: ' بيئة مريحة',
      clinic_gallery_description: 'تم تصميم عيادتنا المتطورة لتوفير تجربة مريحة وهادئة لمرضانا.',
      our_clinic: 'عيادتنا',
      find_us: 'أين نحن',
      visit_our: 'قم بزيارة',
      dental_clinic: 'عيادة الأسنان',
      location_description: 'نحن نقع في موقع مناسب في المنصورة، مصر. قم بزيارتنا اليوم للحصول على استشارة.',
      address: 'العنوان',
      working_hours: 'ساعات العمل',
      working_hours_details: 'الأحد إلى الخميس: 10 صباحًا - 8 مساءً\nالجمعة: 2 ظهرًا - 8 مساءً\nالسبت: 10 صباحًا - 6 مساءً',
      contact_info: 'معلومات الاتصال',
      map_placeholder: 'خريطة موقع العيادة',
      about_service: 'عن هذه الخدمة',
      benefits: 'الفوائد',
      treatment_process: 'مراحل العلاج',
      common_questions: 'الأسئلة الشائعة',
      initial_consultation: 'الاستشارة الأولية',
      initial_consultation_desc: 'فحص شامل لحالة أسنانك ومناقشة خيارات العلاج.',
      preparation: 'التحضير',
      preparation_desc: 'تحضير الأسنان وأخذ قوالب للترميمات المصنوعة خصيصًا.',
      fitting: 'التجربة',
      fitting_desc: 'تجربة الترميمات للتأكد من الملاءمة والمظهر المناسبين.',
      final_placement: 'التثبيت النهائي',
      final_placement_desc: 'تثبيت دائم للترميمات مع التعديلات النهائية للحصول على إطباق مثالي وراحة.',
      treatment: 'العلاج',
      treatment_desc: 'وضع عوامل التبييض المهنية لتفتيح لون الأسنان.',
      aftercare: 'العناية اللاحقة',
      aftercare_desc: 'تعليمات للحفاظ على النتائج ومنع التصبغ المستقبلي.',
      implant_placement: 'زراعة الغرسة',
      implant_placement_desc: 'الزراعة الجراحية للغرسة التيتانيوم في عظم الفك.',
      healing_period: 'فترة الشفاء',
      healing_period_desc: 'السماح للغرسة بالاندماج مع العظم على مدى عدة أشهر.',
      final_restoration: 'الترميم النهائي',
      final_restoration_desc: 'وضع التاج على الغرسة للحصول على مظهر ووظيفة طبيعية.',
      treatment_planning: 'تخطيط العلاج',
      treatment_planning_desc: 'إنشاء خطة مخصصة لمحاذاة الأسنان بشكل مثالي.',
      braces_fitting: 'تركيب التقويم',
      braces_fitting_desc: 'تثبيت أجهزة تقويم الأسنان لبدء عملية المحاذاة.',
      regular_adjustments: 'التعديلات المنتظمة',
      regular_adjustments_desc: 'زيارات دورية لتعديل الأجهزة ومراقبة التقدم.',
      book_appointment_desc: 'احجز موعدك اليوم لمعرفة المزيد عن هذه الخدمة وكيف يمكن أن تفيدك.',
      duration: 'المدة',
      minutes: 'دقيقة',
      expertise: 'الخبرة',
      expert_dentist: 'طبيب أسنان خبير',
      safety: 'السلامة',
      advanced_protocols: 'بروتوكولات سلامة متقدمة',
      have_questions: 'لديك أسئلة؟',
      contact_us_desc: 'فريقنا هنا للإجابة على أي أسئلة قد تكون لديك حول هذه الخدمة.',
      ready_to_transform: 'هل أنت مستعد لتحويل ابتسامتك؟',
      transform_smile_desc: 'احجز استشارة اليوم واتخذ الخطوة الأولى نحو ابتسامة أكثر صحة وجمالاً.',
      book_consultation: 'احجز استشارة',
      service_not_found: 'الخدمة غير موجودة',
      service_not_found_desc: 'تعذر العثور على الخدمة المطلوبة.',
      dental_crowns_benefit1: 'استعادة القدرة على المضغ بشكل طبيعي',
      dental_crowns_benefit2: 'الحفاظ على هيكل عظام الفك',
      dental_crowns_benefit3: 'مظهر طبيعي',
      dental_crowns_benefit4: 'حل طويل الأمد',
      teeth_whitening_benefit1: 'ابتسامة أكثر إشراقًا',
      teeth_whitening_benefit2: 'إزالة البقع والتصبغات',
      teeth_whitening_benefit3: 'إجراء سريع وآمن',
      teeth_whitening_benefit4: 'نتائج ملحوظة فورية',
      dental_implants_benefit1: 'استبدال دائم للأسنان',
      dental_implants_benefit2: 'منع فقدان العظام',
      dental_implants_benefit3: 'مظهر ووظيفة طبيعية',
      dental_implants_benefit4: 'لا تأثير على الأسنان المجاورة',
      orthodontics_benefit1: 'تصحيح محاذاة الأسنان',
      orthodontics_benefit2: 'تحسين وظيفة المضغ',
      orthodontics_benefit3: 'خيارات علاج متعددة',
      orthodontics_benefit4: 'نتائج دائمة',
      dental_crowns_faq1_question: 'كم تدوم تيجان الأسنان؟',
      dental_crowns_faq1_answer: 'مع العناية المناسبة، يمكن أن تدوم تيجان الأسنان 10-15 سنة أو أكثر.',
      dental_crowns_faq2_question: 'هل الإجراء مؤلم؟',
      dental_crowns_faq2_answer: 'يتم إجراء العملية تحت التخدير الموضعي، لذلك لا ينبغي أن تشعر بالألم أثناء العلاج.',
      teeth_whitening_faq1_question: 'كم تدوم نتائج تبييض الأسنان؟',
      teeth_whitening_faq1_answer: 'تدوم النتائج عادة 1-3 سنوات، اعتمادًا على النظام الغذائي وعادات نظافة الفم.',
      teeth_whitening_faq2_question: 'هل تبييض الأسنان آمن؟',
      teeth_whitening_faq2_answer: 'نعم، تبييض الأسنان المهني آمن عندما يتم إجراؤه بواسطة متخصصين مؤهلين في طب الأسنان.',
      dental_implants_faq1_question: 'كم تستغرق عملية الزراعة؟',
      dental_implants_faq1_answer: 'تستغرق العملية بأكملها عادة 3-6 أشهر، بما في ذلك وقت الشفاء.',
      dental_implants_faq2_question: 'هل زراعات الأسنان مغطاة بالتأمين؟',
      dental_implants_faq2_answer: 'تختلف التغطية حسب خطة التأمين. يمكننا مساعدتك في تحديد تغطيتك وخيارات التمويل.',
      orthodontics_faq1_question: 'كم من الوقت سأحتاج لارتداء التقويم؟',
      orthodontics_faq1_answer: 'يختلف وقت العلاج، ولكنه يتراوح عادة بين 12-24 شهرًا حسب التعقيد.',
      orthodontics_faq2_question: 'هل يمكن للبالغين الحصول على علاج تقويم الأسنان؟',
      orthodontics_faq2_answer: 'نعم، علاج تقويم الأسنان فعال للمرضى من جميع الأعمار.',
      dr_name: 'د. محمد خشبه',
      loading: 'جاري التحميل',
      working_hours_short: 'أحد-خميس: ١٠ص-٨م',
      clinic_address: 'المنصورة، مصر',
      training_courses: 'الدورات التدريبية',
      free_consultation: 'استشارة مجانية',
      premium_services: 'خدمات مميزة',
      specialized_dental_care: 'رعاية أسنان متخصصة',
      premium_services_desc: 'نقدم خدمات أسنان مميزة للمرضى ذوي الاحتياجات الخاصة والتوقعات العالية.',
      smile_makeover: 'تجميل الابتسامة',
      smile_makeover_desc: 'تحول كامل لابتسامتك من خلال مجموعة مخصصة من الإجراءات التجميلية.',
      advanced_orthodontics: 'تقويم الأسنان المتقدم',
      advanced_orthodontics_desc: 'علاجات تقويم الأسنان المتطورة لمشاكل المحاذاة المعقدة ومشاكل الفك.',
      laser_dentistry: 'طب الأسنان بالليزر',
      laser_dentistry_desc: 'إجراءات غير جراحية باستخدام تقنية الليزر المتقدمة للعلاجات الدقيقة والمريحة.',
      learn_more: 'اعرف المزيد',
      premium_consultation: 'استشارة مميزة',
      services_title: 'خدماتنا الشاملة لطب الأسنان',
      services_subtitle: 'رعاية متخصصة لجميع احتياجات أسنانك',
      services_overview: 'نقدم مجموعة واسعة من خدمات طب الأسنان لتلبية جميع احتياجات صحة الفم. من الرعاية الوقائية إلى الإجراءات التجميلية المتقدمة، نحن نغطي كل شيء.',
      dental_care_excellence: 'التميز في رعاية الأسنان',
      why_choose_us_desc: 'نجمع بين الخبرة والتكنولوجيا المتقدمة والرعاية الشخصية لتوفير أفضل تجربة لطب الأسنان.',
      experienced_team: 'فريق ذو خبرة',
      experienced_team_desc: 'فريقنا من محترفي طب الأسنان ذوي المهارات العالية ملتزم بتقديم رعاية استثنائية.',
      advanced_technology: 'تكنولوجيا متقدمة',
      advanced_technology_desc: 'نستخدم أحدث تقنيات طب الأسنان لضمان تشخيصات دقيقة وعلاجات فعالة.',
      learn_more_about_us: 'اعرف المزيد عنا',
      quality_point_1_title: 'رعاية متمحورة حول المريض',
      quality_point_1_desc: 'نحن نعطي الأولوية لراحتك ورفاهيتك طوال زيارتك لطبيب الأسنان.',
      quality_point_2_title: 'نهج شامل',
      quality_point_2_desc: 'نهجنا الشامل يأخذ في الاعتبار صحتك العامة واحتياجات أسنانك الخاصة.',
      quality_point_3_title: 'تواصل شفاف',
      quality_point_3_desc: 'نشرح جميع خيارات العلاج والتكاليف قبل المضي قدمًا في أي إجراء.',
      quality_point_4_title: 'التعليم المستمر',
      quality_point_4_desc: 'يقوم فريقنا بتحديث معرفتهم ومهاراتهم بانتظام مع أحدث التطورات في طب الأسنان.',
      insurance_payment: 'خيارات التأمين والدفع',
      insurance_payment_desc: 'نحن نعمل مع مجموعة متنوعة من مزودي التأمين ونقدم خيارات دفع مرنة لجعل رعاية الأسنان في متناول الجميع.',
      insurance_1: 'ميتلايف',
      insurance_2: 'سيجنا',
      insurance_3: 'أيتنا',
      insurance_4: 'دلتا دينتال',
      payment_questions: 'أسئلة عن الدفع؟',
      appointment_title: 'هل أنت مستعد لتحديد موعد زيارتك؟',
      gallery_images: 'صور المعرض',
      before_after: 'قبل وبعد',
      gallery_title: 'تحولات الأسنان لدينا',
      gallery_subtitle: 'شاهد النتائج الرائعة التي نحققها لمرضانا',
      case_study: 'دراسة حالة',
      view_all_cases: 'عرض جميع الحالات',
      clinic_photos: 'صور العيادة',
      clinic_photos_title: 'مرفقنا الحديث',
      clinic_photos_desc: 'خذ جولة في عيادة الأسنان المتطورة لدينا',
      contact_us: 'اتصل بنا'
    }
  });

  useEffect(() => {
    // Set document direction based on language
    document.documentElement.setAttribute('dir', language === 'ar' ? 'rtl' : 'ltr');
    
    // Set language-specific classes for styling
    if (language === 'ar') {
      document.documentElement.classList.add('rtl');
      document.documentElement.classList.remove('ltr');
    } else {
      document.documentElement.classList.add('ltr');
      document.documentElement.classList.remove('rtl');
    }
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
